### ISSUE TITLE
关于在ITS-1801线路板基础上开发除湿机功能

### ISSUE THREAD

**Issue by lzly0302** [seekteam/issues_outside#11]
1、发布除湿机层次图，功能按层次图要求实现。
2、发布ITS-1801主板除湿机版本程序

**Comment by lzly0302** [comment]
[除湿机层次图_V1.1_20200902.pdf](https://github.com/seekteam/issues_outside/files/5180719/_V1.1_20200902.pdf)

**Comment by lzly0302** [comment]
[its1801_dhm_Basic_V1.0_20200907.zip](https://github.com/seekteam/issues_outside/files/5180739/its1801_dhm_Basic_V1.0_20200907.zip)

**Comment by lzly0302** [comment]
[its1801_dhm_Basic_V1.1_20200908.bin.zip](https://github.com/seekteam/issues_outside/files/5185491/its1801_dhm_Basic_V1.1_20200908.bin.zip)
以现在的版本为主，V1.0作废

**Comment by yingsi951** [comment]
以上除湿机层次图V1.1版本，及程序V1.1版本已收到，辛苦！

**Comment by lzly0302** [comment]
在V1.1基础上增加风阀切换功能，程序版本更新为V1.2
[its1801_dhm_Basic_V1.2_20200915.zip](https://github.com/seekteam/issues_outside/files/5222892/its1801_dhm_Basic_V1.2_20200915.zip)

**Comment by yingsi951** [comment]
> 在V1.1基础上增加风阀切换功能，程序版本更新为V1.2
> [its1801_dhm_Basic_V1.2_20200915.zip](https://github.com/seekteam/issues_outside/files/5222892/its1801_dhm_Basic_V1.2_20200915.zip)

V1.2版本程序已收到，谢谢林工！

**Comment by lzly0302** [comment]
[its1801_dhm_Basic_V1.3_20201117.bin.zip](https://github.com/seekteam/issues_outside/files/5551473/its1801_dhm_Basic_V1.3_20201117.bin.zip)
[除湿机层次图_V1.2_20201117.pdf](https://github.com/seekteam/issues_outside/files/5551498/_V1.2_20201117.pdf)

进风温度传感器、低温盘管温度传感器及高温盘管温度传感器更改传感器型号后程序及层次图修正。

**Comment by yingsi951** [comment]
除湿机项目需求屏幕上电开机之后，先开启风阀，2S后再开启电机（包括直流电机和交流电机），请林工帮忙安排修改一下层次图及主板程序吧，谢谢！

**Comment by lzly0302** [comment]
[除湿机层次图_V1.1_20210121.pdf](https://github.com/seekteam/issues_outside/files/5846618/_V1.1_20210121.pdf)
@yingsi951 上传新的层次图

**Comment by yingsi951** [comment]
陈总监您好，关于1801除湿机线路板有2个逻辑需求需要变更一下：
1、化霜逻辑：低温盘管温度由0度改为2度
2、进风温度保护：进入条件，进风温度由＞45度改为＞35度；退出条件，进风温度由34度改为＜33度（详见附件逻辑图片）

以上固件及层次图变更，还请陈总监帮忙安排评估一下，谢谢！

![360截图168201217776126](https://user-images.githubusercontent.com/67322226/106707346-04cbee80-662c-11eb-9f50-fb7ac0258495.png)
