### ISSUE TITLE
关于ITS-1801线路板新增读取产品说明书需求 20200630

### ISSUE THREAD

**Issue by yingsi951** [seekteam/issues_outside#4]
ITS-1801线路板新增读取产品说明书需求，需帮忙安排更新ITS-1801线路板固件（需求：1、新控制器与新固件配合可以正常刷出说明书；2、新控制器与老固件配合无法刷出说明书，但是之前的功能均保持不变，可以正常使用；3、老控制器与新固件配合无法刷出来说明书，但是之前的功能均保持不变，可以正常使用），谢谢！

需求人：MA-研发部-宋静超

**Comment by KrogeChen** [comment]
具体的做法是增加URL的存储字节，增加到512byte。
2点和3点无法保证(牵扯到屏的具体运行方式），但理论上讲问题不大，此风险需要你们自己承担。
此项目预计需要4个人工的费用，合计12000.
@yingsi951 确定后，提供固件。

**Comment by yingsi951** [comment]
陈总监您好，费用已确认可以，请帮忙确保LS7.33+Wi-Fi（LS7.33）可以兼容，谢谢！交期确认后还麻烦帮忙提供一下，辛苦！

**Comment by KrogeChen** [comment]
[ITS1801_P8109_R20200701.zip](https://github.com/seekteam/issues_outside/files/4855394/ITS1801_P8109_R20200701.zip)
@yingsi951 URL的长度支持到510byte。

**Comment by yingsi951** [comment]
陈总监您好，新的ITS-1801固件配合LS7.33需求不连接传感器模块时不显示CO2、PM2.5和湿度，加了产品说明书的读写功能，还请您给帮忙更新一下固件，谢谢！

**Comment by KrogeChen** [comment]
[ITS1801_P8109_R20200703.zip](https://github.com/seekteam/issues_outside/files/4867184/ITS1801_P8109_R20200703.zip)
@yingsi951 上述固件支持传感器区留白显示
